/**
 * Icon Map — lucide-react-native 아이콘을 소문자 키로 매핑
 * DB에 저장된 아이콘 이름(예: 'moon', 'pill')을 실제 컴포넌트로 변환
 */
import type {LucideIcon} from 'lucide-react-native';
import {
  Moon,
  Sun,
  Star,
  Heart,
  Coffee,
  Book,
  BookOpen,
  Briefcase,
  Calendar,
  Camera,
  Car,
  Check,
  Clock,
  Cloud,
  Code,
  Dumbbell,
  Edit3,
  Eye,
  Film,
  Flag,
  Flame,
  Gift,
  Globe,
  Headphones,
  Home,
  Image,
  Inbox,
  Key,
  Laptop,
  Leaf,
  Lightbulb,
  Link,
  Mail,
  Map,
  MapPin,
  MessageCircle,
  Mic,
  Monitor,
  Music,
  Navigation,
  PenTool,
  Phone,
  Pill,
  Pizza,
  Plane,
  Play,
  Plus,
  Rocket,
  Save,
  Search,
  Send,
  Shield,
  ShoppingBag,
  ShoppingCart,
  Smile,
  Sparkles,
  Target,
  ThumbsUp,
  Trash2,
  Tv,
  Umbrella,
  Users,
  Utensils,
  Wallet,
  Watch,
  Wifi,
  Wind,
  Zap,
} from 'lucide-react-native';

const ICON_MAP: Record<string, LucideIcon> = {
  moon: Moon,
  sun: Sun,
  star: Star,
  heart: Heart,
  coffee: Coffee,
  book: Book,
  'book-open': BookOpen,
  briefcase: Briefcase,
  calendar: Calendar,
  camera: Camera,
  car: Car,
  check: Check,
  clock: Clock,
  cloud: Cloud,
  code: Code,
  dumbbell: Dumbbell,
  'edit-3': Edit3,
  eye: Eye,
  film: Film,
  flag: Flag,
  flame: Flame,
  gift: Gift,
  globe: Globe,
  headphones: Headphones,
  home: Home,
  image: Image,
  inbox: Inbox,
  key: Key,
  laptop: Laptop,
  leaf: Leaf,
  lightbulb: Lightbulb,
  link: Link,
  mail: Mail,
  map: Map,
  'map-pin': MapPin,
  'message-circle': MessageCircle,
  mic: Mic,
  monitor: Monitor,
  music: Music,
  navigation: Navigation,
  'pen-tool': PenTool,
  phone: Phone,
  pill: Pill,
  pizza: Pizza,
  plane: Plane,
  play: Play,
  plus: Plus,
  rocket: Rocket,
  save: Save,
  search: Search,
  send: Send,
  shield: Shield,
  'shopping-bag': ShoppingBag,
  'shopping-cart': ShoppingCart,
  smile: Smile,
  sparkles: Sparkles,
  target: Target,
  'thumbs-up': ThumbsUp,
  'trash-2': Trash2,
  tv: Tv,
  umbrella: Umbrella,
  users: Users,
  utensils: Utensils,
  wallet: Wallet,
  watch: Watch,
  wifi: Wifi,
  wind: Wind,
  zap: Zap,
};

/**
 * 아이콘 이름을 lucide-react-native 컴포넌트로 변환
 * phosphor-* 접두사는 지원하지 않음 (null 반환)
 */
export function resolveTodoIcon(iconName: string | null | undefined): LucideIcon | null {
  if (!iconName) return null;
  if (iconName.startsWith('phosphor-')) return null;

  const key = iconName.toLowerCase().trim();
  return ICON_MAP[key] ?? null;
}
