/**
 * Icon Map — lucide-react-native 아이콘을 소문자 키로 매핑
 * DB에 저장된 아이콘 이름(예: 'moon', 'pill')을 실제 컴포넌트로 변환
 */
import type {LucideIcon} from 'lucide-react-native';
import {
  Moon,
  Sun,
  Star,
  Heart,
  Coffee,
  Book,
  BookOpen,
  Briefcase,
  Calendar,
  Camera,
  Car,
  Check,
  Clock,
  Cloud,
  Code,
  Dumbbell,
  Edit3,
  Eye,
  Film,
  Flag,
  Flame,
  Gift,
  Globe,
  Headphones,
  Home,
  Image,
  Inbox,
  Key,
  Laptop,
  Leaf,
  Lightbulb,
  Link,
  Mail,
  Map,
  MapPin,
  MessageCircle,
  Mic,
  Monitor,
  Music,
  Navigation,
  PenTool,
  Phone,
  Pill,
  Pizza,
  Plane,
  Play,
  Plus,
  Rocket,
  Save,
  Search,
  Send,
  Shield,
  ShoppingBag,
  ShoppingCart,
  Smile,
  Sparkles,
  Target,
  ThumbsUp,
  Trash2,
  Tv,
  Umbrella,
  Users,
  Utensils,
  Wallet,
  Watch,
  Wifi,
  Wind,
  Zap,
} from 'lucide-react-native';

const ICON_MAP: Record<string, LucideIcon> = {
  moon: Moon,
  sun: Sun,
  star: Star,
  heart: Heart,
  coffee: Coffee,
  book: Book,
  'book-open': BookOpen,
  briefcase: Briefcase,
  calendar: Calendar,
  camera: Camera,
  car: Car,
  check: Check,
  clock: Clock,
  cloud: Cloud,
  code: Code,
  dumbbell: Dumbbell,
  'edit-3': Edit3,
  eye: Eye,
  film: Film,
  flag: Flag,
  flame: Flame,
  gift: Gift,
  globe: Globe,
  headphones: Headphones,
  home: Home,
  image: Image,
  inbox: Inbox,
  key: Key,
  laptop: Laptop,
  leaf: Leaf,
  lightbulb: Lightbulb,
  link: Link,
  mail: Mail,
  map: Map,
  'map-pin': MapPin,
  'message-circle': MessageCircle,
  mic: Mic,
  monitor: Monitor,
  music: Music,
  navigation: Navigation,
  'pen-tool': PenTool,
  phone: Phone,
  pill: Pill,
  pizza: Pizza,
  plane: Plane,
  play: Play,
  plus: Plus,
  rocket: Rocket,
  save: Save,
  search: Search,
  send: Send,
  shield: Shield,
  'shopping-bag': ShoppingBag,
  'shopping-cart': ShoppingCart,
  smile: Smile,
  sparkles: Sparkles,
  target: Target,
  'thumbs-up': ThumbsUp,
  'trash-2': Trash2,
  tv: Tv,
  umbrella: Umbrella,
  users: Users,
  utensils: Utensils,
  wallet: Wallet,
  watch: Watch,
  wifi: Wifi,
  wind: Wind,
  zap: Zap,
};

/**
 * 아이콘 이름을 lucide-react-native 컴포넌트로 변환
 * phosphor-* 접두사는 지원하지 않음 (null 반환)
 */
export function resolveTodoIcon(iconName: string | null | undefined): LucideIcon | null {
  if (!iconName) return null;
  if (iconName.startsWith('phosphor-')) return null;

  const key = iconName.toLowerCase().trim();
  return ICON_MAP[key] ?? null;
}

/**
 * 카테고리별 아이콘 그룹 (아이콘 피커용)
 */
export interface IconCategory {
  label: string;
  icons: {key: string; Icon: LucideIcon}[];
}

export const ICON_CATEGORIES: IconCategory[] = [
  {
    label: '일상',
    icons: [
      {key: 'home', Icon: Home},
      {key: 'coffee', Icon: Coffee},
      {key: 'utensils', Icon: Utensils},
      {key: 'shopping-cart', Icon: ShoppingCart},
      {key: 'shopping-bag', Icon: ShoppingBag},
      {key: 'pizza', Icon: Pizza},
      {key: 'gift', Icon: Gift},
      {key: 'umbrella', Icon: Umbrella},
    ],
  },
  {
    label: '업무',
    icons: [
      {key: 'briefcase', Icon: Briefcase},
      {key: 'laptop', Icon: Laptop},
      {key: 'monitor', Icon: Monitor},
      {key: 'code', Icon: Code},
      {key: 'mail', Icon: Mail},
      {key: 'calendar', Icon: Calendar},
      {key: 'inbox', Icon: Inbox},
      {key: 'wallet', Icon: Wallet},
    ],
  },
  {
    label: '건강',
    icons: [
      {key: 'heart', Icon: Heart},
      {key: 'pill', Icon: Pill},
      {key: 'dumbbell', Icon: Dumbbell},
      {key: 'leaf', Icon: Leaf},
      {key: 'smile', Icon: Smile},
      {key: 'eye', Icon: Eye},
    ],
  },
  {
    label: '이동',
    icons: [
      {key: 'car', Icon: Car},
      {key: 'plane', Icon: Plane},
      {key: 'map-pin', Icon: MapPin},
      {key: 'navigation', Icon: Navigation},
      {key: 'map', Icon: Map},
      {key: 'globe', Icon: Globe},
    ],
  },
  {
    label: '소통',
    icons: [
      {key: 'phone', Icon: Phone},
      {key: 'message-circle', Icon: MessageCircle},
      {key: 'send', Icon: Send},
      {key: 'users', Icon: Users},
      {key: 'mic', Icon: Mic},
      {key: 'headphones', Icon: Headphones},
    ],
  },
  {
    label: '창작',
    icons: [
      {key: 'camera', Icon: Camera},
      {key: 'music', Icon: Music},
      {key: 'film', Icon: Film},
      {key: 'pen-tool', Icon: PenTool},
      {key: 'image', Icon: Image},
      {key: 'book', Icon: Book},
      {key: 'book-open', Icon: BookOpen},
      {key: 'edit-3', Icon: Edit3},
    ],
  },
  {
    label: '기타',
    icons: [
      {key: 'star', Icon: Star},
      {key: 'flag', Icon: Flag},
      {key: 'flame', Icon: Flame},
      {key: 'rocket', Icon: Rocket},
      {key: 'zap', Icon: Zap},
      {key: 'target', Icon: Target},
      {key: 'lightbulb', Icon: Lightbulb},
      {key: 'sparkles', Icon: Sparkles},
      {key: 'shield', Icon: Shield},
      {key: 'moon', Icon: Moon},
      {key: 'sun', Icon: Sun},
      {key: 'cloud', Icon: Cloud},
      {key: 'wind', Icon: Wind},
    ],
  },
];
